name: immichframe
services:
  immichframe:
    container_name: immichframe
    image: ghcr.io/immichframe/immichframe:v1.0.31.0@sha256:7a697c43c9a859014dcd5adad0fa4c1c450e9fc9e1c75e8b62c94197cdf7b584
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      TZ: "Europe/Zurich"
